language: go
sudo: false

services:
  - docker

env:
  global:
    # DOCKER_USER
    - secure: "qNgI983IedO9+MTB3cO9EcUBkJb99yF2hqgzDUAXGoI+wj9ofdjc5L+hJXF11nbTwGir8FeeWt2qpi4OHOKO89wsNTye9SlvgNP80yrq005iC7oMsyAcq7qwYx8cPoHx09CPlr+z8eh6vy3QsADutwaEKs8DdnzUAnORYUTcDsuqy/dt+FT4xSwJQmNt/NSuRORS71aJQpnTpQ5gg23z+9GVz99NtiODMK3qN9z/aJUzJSW3iNWBat4Ye5p6L9Uh07DEXJXuegXMDU5JZN6bAd/wihJYfIaUxvXdun8R4yHLMSL57dpjG193Qiou4age6hHRgWqiNKe4kFaVtE8IAFHsB4xTR9csBlsRb2hCko9GtOnmInPrGx+9/yMs/wItMC/yeIqTf4Idj7IQ+ySh1ftC26GG2F7ZnLVqyC/82MD5L3LaXGAjyGuxqDSjNw1V6/H5SWqN49QNNWKJldV0nF+z7htXwEDARiBsicK9uy+Sx1Z+1H72QI4j1HNrRM2Ktr69HsgD8M1eJ4o4JuNFmMm34uOk12A+dUpB/NrjXFJYfB3MW4QysvUMMdkM1IXpFQ5N8MZ2Ozmb5Zh5EJ7BKFSm+LzlZD6CHPyHdVOpYJQjxzUsXKM4qPk5+5LmlrJERRAuXFGsfVDGvmChMutV740xqoUnQbOepJcpqlJ4+6g="
    # DOCKER_PASS
    - secure: "Cl4C0LcdCNICnbO9Ivpe8lsv9e7/MUNsar9hB5pnVfZN99GLCXD3daK0SS9cOym0mwRZbsz7DRU27V0n2bCXweh3c0lPfzVWkhqTE9wteDEWgz6tockUErhCCIhP/B2r3B6fr+uDuVSxt3xzEZRwIUqwlcM9Glqgugt9sx+VSM5ou7iTMSW9xXjr1qiTslHRTANQDvjyEMhRsrejXmFHp33GMqC9uYVmlR+lBwBKglbABOG9hTLNE+VEazEIt2RTiGkS1soIt/+wB+30Xx3qkbL82SvMXyDCVSDTf+PdsGt63ALZZoqMoK5l15tQQwyjm90JAPA02h1BsMeTcONM1tvAHnq43eBEXTZtKEfF6BO6wDrMdorkl1bOs0OHRSsyLDi974WYxnfP+WJcIK69C5Cscf+gWxMmV4Ybazjx9Bgw1kL8Kr2iNagc3K9MpZ3hV43z99XIUlrwJNZYVFcDyQGU65zDfeeMOTN/R0SgxhTk2n2biqb66mzyDS+5MPijDpyApJSM3AVALna0CLg28K4QjmP2g8oGgmiQHIydzFIlyFEvePp7qr7EzCURRIwGbdN73YFIN6UzsnhR2SncLOBfoS4KEQp895mO+mL5wq2hUyl58OD/evamp7a8rkGdm/rhbJ50boIsQ/Dy2MO+V8b+YKuVTvn6stNCoVrZXY0="
    - GO111MODULE=on

go:
  - 1.12.x

matrix:
  fast_finish: true

before_install:
  - make init

script:
  - make status verify

before_deploy:
  - go mod vendor
  - make status release docker-build docker-images
  - echo "Deploying to GitHub and Quay ..."

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - make -e docker-login docker-push
    on:
      repo: VirtusLab/kubedrainer
      tags: true
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: BQNvmALrlsflpkEQP2asPd6mVJ4xIskFtTfFdaNcCz7+zv8K+rAAla69pJ8NFSOaQPRdA9fInUsnnyukkOF7JPmYJk3vxBHegeBvX1d2pRYLh9MshpyAiCq/mEOEIk2gQr5FnlEz7UhMuFeTOfvv1tCWf6yTsYjNfv+PquxVpiHUG/mFxtmdeLawwiJtGSjcBHYTHb895u2hpBrekKNQTfty+L0cRDyxX7ovYX402Bc9faiEyUk/1F55J5Jap30C4X/gSFxsC+NvhXBLcWyuh4Y/zLJvd4cAmw7pi26zDb/QTUmPdyIhJ+ysml9M/O317OXW3ypNxdsDAvzvjm+w5KN0AI+5HnTNI4YoS4N4spQNa0PgDLH7zc/3/iOWtSNA+x6wI9Dri/KMiI6f62VKFSicYSa9c6vTQscN62DPh+YSRgyxoBSkHPuW8j5uOU6TYTLObPcc7rLFDGxk7opRODbn4zUPhxqJMk1MhRUKw9jciPMYPcWne4R0Ua8w/HmdSWfhcPDfz++qz29sEiVS+gLIqI7SDyc6mH062+Q0+OQJ6ej8jJM/dl5hCHZIWmknGQ7YxxI5A/KPSpfmt9SrWhRVfG1VULnrotK2PsU/uPkdKlCWskuwkBQ6Ib2qj9dEB9CXwyKkwjLqRd/OYsnD9qd6hQU5XMrhsuNw3jjqtXY=
    on:
      repo: VirtusLab/kubedrainer
      tags: true
    file:
      - cross/kubedrainer-darwin-amd64
      - cross/kubedrainer-darwin-amd64.md5
      - cross/kubedrainer-darwin-amd64.sha256
      - cross/kubedrainer-linux-arm
      - cross/kubedrainer-linux-arm.md5
      - cross/kubedrainer-linux-arm.sha256
      - cross/kubedrainer-linux-arm64
      - cross/kubedrainer-linux-arm64.md5
      - cross/kubedrainer-linux-arm64.sha256
      - cross/kubedrainer-linux-amd64
      - cross/kubedrainer-linux-amd64.md5
      - cross/kubedrainer-linux-amd64.sha256
      - cross/kubedrainer-windows-amd64
      - cross/kubedrainer-windows-amd64.md5
      - cross/kubedrainer-windows-amd64.sha256

cache:
  directories:
    - vendor
